### ISSUE TITLE
Lint test - Lint for called functions in `main.nf`

### ISSUE THREAD

**Issue by ggabernet** [nf-core/tools#1043]
## Is your feature request related to a problem? Please describe

Sometimes during template merge in `main.nf` people accidentally remove important functionality there such as:
- Function to print header: `log.info Headers.nf_core(workflow, params.monochrome_logs)`
- Function to print params help: `log.info NfcoreSchema.params_help(workflow, params, json_schema, command)`
- Function to validate parameters: `NfcoreSchema.validateParameters(params, json_schema, log)`
- Other checks: `check_conda_channels`, `aws_batch`, `hostname`
- Print Summary params: `log.info NfcoreSchema.params_summary_log(workflow, params, json_schema)`

## Describe the solution you'd like

If the real workflow is gonna be in a separate file from now on then `main.nf` could be added to the linting for "files that should start like the template". Or alternatively implement linting for `main.nf` so the listed functions are checked for existance.

**Comment by ewels** [comment]
I half wonder if we can wrap all of this into a single function call. Once we get rid of the `summary` stuff for the email especially.

Might also be nice to move the "typical command" thing into the schema somewhere so that it doesn't need to be defined in the workflow for the header.. 🤔

**Comment by drpatelh** [comment]
Yup, I agree it is very tricky to see whether you have missed stuff. These changes are mostly due to the state of flux with the content of the DSL2 pipeline template but hopefully, once we have settled on something more permanent it should be easier to manage. I have re-organised and renamed most of the files / functions you highlighted in the original comment to have a single function call as @ewels mentioned in the most up-to-date DSL2 template in rnaseq. The remnants have been moved here https://github.com/nf-core/rnaseq/pull/622. Be awesome if I can get some comments on the structure there so we can decide on something a little more permanent.

**Comment by ggabernet** [comment]
yeah, having a single function call sounds even better!

**Comment by drpatelh** [comment]
We now have a single function call for this in the template since everything has been moved to the `lib/` directories. There could still be issues when merging template syncs there too but you should get a lint warning suggesing the files aren't the same. https://github.com/nf-core/tools/blob/b48bce26b7da46cb71e4a8f78b68d9ceac579ca6/nf_core/pipeline-template/main.nf#L28
