### ISSUE TITLE
Dockerfile Conventions

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#11]
Just a thought:

Maybe we could have the Dockerfiles in a similar fashion than [here](https://github.com/apeltzer/NGI-ExoSeq/blob/gatk4-jointdiscovery/containers/Dockerfile), to keep things consistent. 

I thought about having the following:

- Dockerfile with very specific import setting (e.g. our standard one, that imports via `conda` all required packages)
- Extra "Requirements.txt" file that is imported by that Dockerfile, containing `conda` packages to be installed

This way we could checksum the Dockerfile (or even provide it via cookiecutter) and then have people only add what kind of dependencies they want in a specific version.

This also provides us with the possibility to create a Tag that is identical to the Tag for the pipeline in NXF = keeping things consistently pulled as well! 

Thoughts?

I will create another issue in cookiecutter to link to this here...

**Comment by ewels** [comment]
Sounds great! See [my comment](https://github.com/SciLifeLab/NGI-ExoSeq/pull/23#issuecomment-370561668) about using an environment yaml file instead of a `requirements.txt`.

Also note that this should be a warn rather than a fail, as not all software packages can be installed through conda.

> This also provides us with the possibility to create a Tag that is identical to the Tag for the pipeline in NXF = keeping things consistently pulled as well!

Can we not do this however the docker file is written? Just a automatic tag setting on quay.io / dockerhub that is triggered by a GitHub release..

**Comment by ewels** [comment]
I think we can close this issue now.. Unless there's something specific to the linting that we should add? Feel free to reopen if so..
