### ISSUE TITLE
Updating handling of `<pipeline directory>` in `nf-core`

### ISSUE THREAD

**Issue by ErikDanielsson** [nf-core/tools#1140]
As was discussed on [slack](https://nfcore.slack.com/archives/CE5LG7WMB/p1625128917485100) it would be good to not have to specify the pipeline directory as the current working directory on the different subcommands of `nf-core` The suggestion is therefore to specify pipeline directory with `--dir <pipeline directory>` with current working directory as default, instead of as `<command> <pipeline directory>`

**Comment by ewels** [comment]
Yup, I think that this would be great :+1:

Will probably need a little testing / refining of what happens if the cwd is not a pipeline directory. Just to make sure that annoying stuff doesn't happen if people run the commands when accidentally in a subfolder etc. I was half wondering about traversing up the file tree to try to find a pipeline in this case, but I think it's probably overkill and easier / safer to just exit nicely.
