### ISSUE TITLE
GitHub dark mode images - syntax update

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#1614]
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to

> The old method of specifying images based on the theme, by using a fragment appended to the URL (`#gh-dark-mode-only` or `#gh-light-mode-only`), is deprecated and will be removed in favor of the new method described above.

So we need to update the template readme, plus any other instances where we are using this method.

**Comment by christopher-hakkaart** [comment]
@ewels 

GitHub renders the HTML picture one to one - meaning using a relative path won't work when it's pushed. The main README is fine because it has master image paths to rely on, but for now pipelines using the template there won't be an absolute path to use.

Do you have any suggestions for a work around?

[Blog post describing the problem](https://www.stefanjudis.com/notes/how-to-define-dark-light-mode-images-in-github-markdown/#update%3A-github-is-testing-the-%60picture%60-element)

**Comment by maxulysse** [comment]
we can always change template to have an absolute path instead

**Comment by christopher-hakkaart** [comment]
How would that work between local and remote? Update the path if/when a pipeline is pushed to git?

**Comment by maxulysse** [comment]
Only https path I'd assume, so only master branch or dev branch (not optimal, I agree)

**Comment by ewels** [comment]
Yup, I hit exactly this with a Nextflow repo a couple of days ago: https://github.com/nextflow-io/trademark/pull/1#issuecomment-1143292154

It's a bit annoying, but as that blog post you linked to mentions - the new syntax is still in beta. It looks like the [blog post announcing it](https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/) was only a few days ago (May 22nd). So hopefully this will change yet. Regular `<img>` tags work with relative links, after all.

Maybe worth waiting a little while 👍🏻
