### ISSUE TITLE
Make WARN: Found unexpected parameters more prominent

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/tools#1657]
### Description of feature

The warning about an unexpected parameters is almost immediately followed by the whole pipeline header about used parameters etc. often leading to it being too fast gone to even notice it. 

I was wondering if this could be a) made more prominent or if tb) here is a reason why the pipeline shouldn't fail when unrecognized parameters are used. 

For a), some thoughts I had:
reprint statement again when the pipeline finishes (if that is possible) or write it to a log file (or maybe even the multiqc file).

**Comment by fabianegli** [comment]
Is there a really good reason why random arguments should not fail? If not I would make it fail with a clear message what was too much.

**Comment by sralchemab** [comment]
Hi there, I just run a pipeline using `-profile awsbatch` which expects three parameters that are not expected by the pipeline. If this would fail the pipeline, then we wouldn't be able to run any pipeline using awsbatch. I don't think these variables should be added to the core of the pipeline because they are specific to a profile, and this would probably be the same for several other profiles as well.

**Comment by mashehu** [comment]
exoseq is an archived pipeline without any release, so maybe not the best test case...

**Comment by fabianegli** [comment]
Coming back to this: would it be possible to know the list of all parameters, including the ones for the profiles, and thus be more useful with warnings? Or fail? If I am not mistaken a warning is logged for any non-pipeline specific parameter e.g. the ones for the profile?

**Comment by mirpedrol** [comment]
After using the nf-validation plugin, there is a parameter `--validationFailUnrecognisedParams` which will make unrecognised params fail with errors, instead of warnings.
I am going to close the issue as solved, please feel free to reopen it or create a new one in the [nf-validation repo](https://github.com/nextflow-io/nf-validation) if this is still not a good solution :)
