### ISSUE TITLE
Implement 'nf-core subworkflows remove' command

### ISSUE THREAD

**Issue by drpatelh** [nf-core/tools#1886]
Similar to the existing 'nf-core modules remove' command but for subworkflows.

**Comment by awgymer** [comment]
If the desired behaviour is to also remove modules used by the subworkflow then there will need to be logic which can determine if any other subworkflow/workflow independently relies upon the module. 

We could make some assumptions about structure (which I think hold true for any nf-core pipelines) but otherwise you might have to extract the module include paths and resolve them to ensure they are truly pointing to the same module?

**Comment by mashehu** [comment]
added in #2012
