### ISSUE TITLE
Text editor in the base image

### ISSUE THREAD

**Issue by HadrienG** [nf-core/tools#197]
Hi!

Could we add a (any) text editor in the base image? Everytime I run into conda environment issues this happens

```
(base) root@f03990dcbe64:/# vi environment.yml 
bash: vi: command not found
(base) root@f03990dcbe64:/# vim environment.yml 
bash: vim: command not found
(base) root@f03990dcbe64:/# nano environment.yml 
bash: nano: command not found
(base) root@f03990dcbe64:/# pico environment.yml 
bash: pico: command not found
(base) root@f03990dcbe64:/# emacs environment.yml 
bash: emacs: command not found
(base) root@f03990dcbe64:/# ed environment.yml 
bash: ed: command not found
```

I know I can install wathever I want for debugging, but it is still a minor inconvenience 😊 
I understand if we don't get vim (it's 31Mb and _some_ people don't like it)
`nano` is 2Mb so it wouldn't be too bad on the docker size, and usable for everyone.

I went ahead and tagged this low-priority, but tell me what you think!

Best,
Hadrien

**Comment by sven1103** [comment]
Hi @HadrienG ,

what speaks against developing your pipeline using a `conda` profile, that points to a local conda environment. Once you are ready with heavy development and bugfixing, you export the environment and switch to container, e.g. during the pipeline release preparation phase.

What do you think?

Best, Sven

**Comment by HadrienG** [comment]
Hi @sven1103 

I think it is the right way to do it, unfortunately in my case some of my dependencies are linux specific (and I'm on MacOS)

**Comment by sven1103** [comment]
Have you tried Vagrant? I switched to MacOS since 2 weeks, and using Vagrant + VirtualBox to ssh into a CentOS 7 VM, which I use for development and testing.

https://www.vagrantup.com

**Comment by ewels** [comment]
I agree, but also I don't really care about 2MB...

**Comment by HadrienG** [comment]
@sven1103 I might give it a try. 

@ewels It is really a minor issue but I thought it was not just me annoyed by this 😬I can keep installing a text editor whenever I run into docker installs it's not a big deal

**Comment by apeltzer** [comment]
Im happy to add vim and nano, won’t bloat the image too much up I suppose :)

**Comment by apeltzer** [comment]
See #202 for the fix for this :-)

**Comment by sven1103** [comment]
Don't want to make a big thing out of this. I just think that adding dependencies to the base image is a generally bad idea (not only for this use case), especially if it just addresses the development workflow and does not lead to a more stable or add value to the final pipeline. Adding software means adding dependencies, which adds complexity and provokes nasty side effects. Call me paranoid, but that is what I have observed so far. 

Everyone is free to sandbox his or her container for development, but for stable releases, the container environment should be as clean and minimal as possible.

That is my two cents, feel free to beat me now ;)

@HadrienG Please don't feel offended, your issue is valid, and feel free to pm me if you need help regarding Vagrant and sandboxing.

**Comment by HadrienG** [comment]
@sven1103 No offence taken!
