### ISSUE TITLE
'nf-core modules create' changes pytest_modules.yml and displeases prettier

### ISSUE THREAD

**Issue by pinin4fjords** [nf-core/tools#1972]
### Description of the bug

When creating a module with:

```
nf-core modules create foo/bar
```

... tests/config/pytest_modules.yml in the modules repo gets edited to add the new module entry. Unfortunately it also formats the file in a way that upsets prettier, and you need to do:

```
prettier --write tests/config/pytest_modules.yml
```
... to appease the linter when raising a PR. 

Not a massive deal obviously, but could we have the create command edit the file in a way that keeps prettier happy, or else run prettier automatically when doing the create (which might be more robust to future prettier changes)?

### Command used and terminal output

```
> nf-core modules create foo/bar
...

> git git diff ./tests/config/pytest_modules.yml 
diff --git a/tests/config/pytest_modules.yml b/tests/config/pytest_modules.yml
index 6ddf9f3a..db56652c 100644
--- a/tests/config/pytest_modules.yml
+++ b/tests/config/pytest_modules.yml
@@ -1,2845 +1,2849 @@
 abacas:
-  - modules/nf-core/abacas/**
-  - tests/modules/nf-core/abacas/**
+- modules/nf-core/abacas/**
+- tests/modules/nf-core/abacas/**
 
 abricate/run:
-  - modules/nf-core/abricate/run/**
-  - tests/modules/nf-core/abricate/run/**
+- modules/nf-core/abricate/run/**
+- tests/modules/nf-core/abricate/run/**
...

> prettier --write tests/config/pytest_modules.yml 
tests/config/pytest_modules.yml 347ms
                          
> git diff
diff --git a/tests/config/pytest_modules.yml b/tests/config/pytest_modules.yml
index 6ddf9f3a..bedb5c88 100644
--- a/tests/config/pytest_modules.yml
+++ b/tests/config/pytest_modules.yml
@@ -911,6 +911,10 @@ flye:
   - modules/nf-core/flye/**
   - tests/modules/nf-core/flye/**
 
+foo/bar:
+  - modules/nf-core/foo/bar/**
+  - tests/modules/nf-core/foo/bar/**
+
 fq/lint:
   - modules/nf-core/fq/lint/**
   - tests/modules/nf-core/fq/lint/**
```

**Comment by awgymer** [comment]
I think this has possibly always been broken? I found the issue is related to the `CustomDumper` used for `yaml`.
Specifically it implements a fix for indenting lists given in another Github issue, but it implements it incorrectly 😬 

https://github.com/nf-core/tools/blob/dec66abe1c36a8975a952e1f80f045cab65bbf72/nf_core/utils.py#L748-L753

It needs to be changed to set `indentless` to `False` in the actual method. It's a subtle change but achieves what was originally intended. 

```py
def increase_indent(self, flow=False, *args, **kwargs):
        return super().increase_indent(flow=flow, indentless=False)
```

I'm not clear yet if this could break other yaml dumping though and I would suggest we could add an attempt to call prettier on create just as we do when running the main pipeline create command

**Comment by ewels** [comment]
> just as we do when running the main pipeline create command

We do? I thought that this was difficult / impossible as Prettier is an npm package and not in the Python ecoystem (so has to be packaged differently)

**Comment by ewels** [comment]
Hah! @ErikDanielsson you cheeky badger! 🦡  Not sure if I've not seen this before or just forgotten, fairly likely to be the latter. That's one way to get around the problem then I guess..

Would be nice to at least write it into a utils function for reuse if it's going to show up anywhere else.

**Comment by ErikDanielsson** [comment]
:grin: I sneaked it in when making `nf-core create` customisable, since getting prettier linting to pass out of the box would've required a lot of code modifying indentation. So I argued that since we are using prettier for nearly everything else we might as well use it in the `tools` code. It is perhaps a little bit hacky, but I preferred it over a brittle DIY solution.

**Comment by awgymer** [comment]
So I think the solution here is two-fold (maybe three): 
- Apply fix to yaml dumper and test
- Abstract prettier calls and add one to module create
- Highlight the pre-commit options more/better?

**Comment by pinin4fjords** [comment]
FWIW it makes total sense to me to format with the thing you're using to do the linting rather than laboriously anticipating its needs :-).

**Comment by fabianegli** [comment]
With pre-commit the Prettier dependency can be automatically installed in the repo. This could then be used with a call in the form of `pre-commit run prettier --files [file]` This would, however, introduce pre-commit as dependency for production code. Of course this could be optional for the case when Prettier is not installed locally. And the code could check once if Prettier is installed and if it is not fall back to the pre-commit hook and if that fails alert.

**Comment by fabianegli** [comment]
Conceptually -  shouldn't it be possible to just run `nf-core lint --fix`

**Comment by awgymer** [comment]
> Conceptually - shouldn't it be possible to just run `nf-core lint --fix`

`--fix` only attempts some fixes and `lint` doesn't use `prettier` at all anyway

**Comment by fabianegli** [comment]
@awgymer Right, it dies not. But wouldn't it be nice if it did?
