### ISSUE TITLE
--git-remote for custom module repository requires https:// for install (but not other commands)

### ISSUE THREAD

**Issue by kcibul** [nf-core/tools#2006]
### Description of the bug

I noticed some command under `nf-core modules ...` work with a `--git-remote git@...` (e.g. list) but others do not (e.g. install) and fail in a unique way where it keeps rewriting the modules.json.  

It looks like https://github.com/nf-core/tools/blob/master/nf_core/modules/modules_json.py#L378 is what requires http here. 

Would be great if it was consistent so git@ worked everywhere, or nowhere (and was documented more clearly).

### System information

nf-core 2.6

**Comment by lbeltrame** [comment]
Just hit the same snag. We use some modules in a private repository so we need to use SSH access.

**Comment by lbeltrame** [comment]
Further investigation showed that this code path is unlikely to work properly:

This looks for a key that does not exist in `repos` when using `install` (when repos is `None`):

https://github.com/nf-core/tools/blob/dec66abe1c36a8975a952e1f80f045cab65bbf72/nf_core/modules/modules_json.py#L159

This will fail  because the nf-core repositories won't have the required keys when `repos` is `None`:

https://github.com/nf-core/tools/blob/dec66abe1c36a8975a952e1f80f045cab65bbf72/nf_core/modules/modules_json.py#L161

**Comment by apeltzer** [comment]
Also hit us unfortunately already as our internal private repos are all SSH git access via keys only :-(

**Comment by apeltzer** [comment]
Can we add this to 2.7 release? @mashehu ? Cannot even test it entirely at the moment due to this here with our internal setup :-(

**Comment by apeltzer** [comment]
Confirmed with local tests that this now indeed works as intended 💯 🥇 Thanks @mirpedrol for the fix!
