### ISSUE TITLE
Default test pipeline fails if user has AWS credentials set

### ISSUE THREAD

**Issue by tomsing1** [nf-core/tools#2153]
### Description of the bug

I was following @ewels 's [excellent tutorial](https://youtu.be/FtC1Efx7-zU?t=1656) where he demonstrates how a newly instantiated nf-core pipeline comes with test workflow defined out of the box.

On my system my AWS credentials are defined in `/Users/my_username/.aws/credentials`. They are detected and used by nextflow by default. This leads to an authentication error (see below) when nextflow tries to retrieve the example iGenome file from AWS. The error is avoided when I remove my `credentials` file. 

Perhaps you have additional instructions on how to avoid this problem, without having to move my `credentials` file out of the way?

Many thanks!

```
N E X T F L O W  ~  version 22.10.4
Launching `nf-core-pipeline/main.nf` [hopeful_montalcini] DSL2 - revision: 7de5dd7533


------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/pipeline v1.0dev
------------------------------------------------------
Core Nextflow options
  runName                   : hopeful_montalcini
  containerEngine           : docker
  launchDir                 : /Users/sandmann/tmp/training
  workDir                   : /Users/sandmann/tmp/training/work
  projectDir                : /Users/sandmann/tmp/training/nf-core-pipeline
  userName                  : sandmann
  profile                   : test,docker
  configFiles               : /Users/sandmann/tmp/training/nf-core-pipeline/nextflow.config

Input/output options
  input                     : https://raw.githubusercontent.com/nf-core/test-datasets/viralrecon/samplesheet/samplesheet_test_illumina_amplicon.csv
  outdir                    : test_run

Reference genome options
  genome                    : R64-1-1
  fasta                     : s3://ngi-igenomes/igenomes/Saccharomyces_cerevisiae/Ensembl/R64-1-1/Sequence/WholeGenomeFasta/genome.fa

Institutional config options
  config_profile_name       : Test profile
  config_profile_description: Minimal test dataset to check pipeline function

Max job request options
  max_cpus                  : 2
  max_memory                : 6.GB
  max_time                  : 6.h

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use nf-core/pipeline for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/nf-core/pipeline/blob/master/CITATIONS.md
------------------------------------------------------
Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 8F52CJ6G3JDV1AYZ; S3 Extended Request ID: 0rf8nac/5ZMPovnVwzFWFYNC8dWqxZkYPWK69a/CLuWjOKb+z4KXEhGK9pe6f481/+W1TzodtBo=; Proxy: null)

 -- Check script 'nf-core-pipeline/./workflows/pipeline.nf' at line: 15 or see '.nextflow.log' file for more details
```

### Command used and terminal output

```console
nf-core create --name pipeline --description "test pipeline" --author "me"
nextflow run nf-core-pipeline/ -profile test,docker --outdir test_run
```

### System information

`nextflow info`
Version: 22.10.4 build 5836
  Created: 09-12-2022 09:58 UTC (01:58 PDT)
  System: Mac OS X 13.1
  Runtime: Groovy 3.0.13 on OpenJDK 64-Bit Server VM 17.0.3+7-LTS
  Encoding: UTF-8 (UTF-8)

`Hardware`
MacBook Pro

`OS`
Mac OS 13.1 (22C65)

`nf-core tools`
nf-core/tools version 2.7.2
Python 3.11.0

**Comment by ewels** [comment]
This is a known issue and unfortunately I don't have any good short term solutions. Some speed thoughts from my phone:

- The `-profile test` dataset shouldn't normally use AWS-iGenomes, so I'm a little surprised that you hit this issue (the reference genome is usually tiny and hosted on GitHub)
- There is a `params` option to skip loading iGenomes. You'll then need to specify your own reference but it will at least avoid the authentication problem
- There is also a parameter for changing the base of the URL for iGenomes so that you can use your own set.

Longer term solutions:

- Multi-region mirroring of AWS-iGenomes so that they are available in different regions (suggested / discussed but not yet set up)
- Moving towards using RefGenie instead of AWS-iGenomes long term, hence slow movement of anything iGenomes related (on my phone but you should be able to find issues with more details and progress)

**Comment by tomsing1** [comment]
Thanks a lot for the instantaneous reply, very helpful and much appreciated. In case it's useful to the maintainers of the `rnaseq` workflow, I have posted this issue [there](https://github.com/nf-core/rnaseq/issues/925) and am closing it here.

**Comment by drpatelh** [comment]
Re-opened this and transferred and closed https://github.com/nf-core/tools/issues/2156 because this is an issue with the pipeline template and not nf-core/rnaseq. However, be interested to know if the same issue manifests with and without the credentials set. If so, be great if you can open a separate issue on that repo too please.

```
nextflow run nf-core/rnaseq -profile test,docker --outdir ./results
```

The test FastQ files for the pipeline template are actually hosted on Github and not AWS so this shouldn't be the problem. The samplesheet for `-profile test` is:
https://github.com/nf-core/tools/blob/99961bedab1518f592668727a4d692c4ddf3c336/nf_core/pipeline-template/conf/test.config#L25

Which contains raw GitHub URLs. I intentionally used the nf-core/viralrecon data for this reason.

I suspect the permissions issues are occurring because we set `--genome` by default when using `-profile test` in the pipeline template:
https://github.com/nf-core/tools/blob/99961bedab1518f592668727a4d692c4ddf3c336/nf_core/pipeline-template/conf/test.config#L29

This is probably what is conflicting with your permissions and any default regions because the iGenomes data isn't hosted in a multi-region fashion.

As a test you could try to download the fasta file via the AWS CLI and then run with the command below with your local credentials set. If this fixes it then we know it's an AWS iGenomes region issue:

```
aws s3 cp --no-sign-request s3://ngi-igenomes/igenomes/Saccharomyces_cerevisiae/Ensembl/R64-1-1/Sequence/WholeGenomeFasta/genome.fa .
nextflow run nf-core-pipeline/ -profile test,docker --outdir test_run --genome false --fasta ./genome.fa
```

**Comment by tomsing1** [comment]
Thanks a lot for following up on this! Unfortunately, I still get an error when my `credentials` file is in place.
Looking at the stderr, I think this line is causing the problem now:

`Jan-11 07:57:35.962 [Actor Thread 7] DEBUG nextflow.file.FileHelper - Started plugin 'nf-amazon' required to handle file: s3://nf-core-awsmegatests/rnaseq/input_data/minimal/GSE110004/SRR6357076_1.fastq.gz`

e.g. it looks like the test profile is retrieving a FASTQ file from S3 as well.

Here are the commands I ran
```
# reproducing the previously reported error
> nextflow run nf-core/rnaseq -profile test,docker -r 3.10.1 --outdir test_run 

Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 3DNMGXQ9GZ24QVE5; S3 Extended Request ID: y9/gCRQUMHt09LDjRO417J2vR89o+UKpNksH6DSlY9Shl7LHSGLR0hfCDcViDglbc9OIZYT0Bu4=; Proxy: null)

# downloading the genome first
> aws s3 cp --no-sign-request s3://ngi-igenomes/igenomes/Saccharomyces_cerevisiae/Ensembl/R64-1-1/Sequence/WholeGenomeFasta/genome.fa .
> nextflow run nf-core/rnaseq -profile test,docker -r 3.10.1 --outdir test_run --genome false --fasta ./genome.fa

Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 7STE2KS3K9KKZD52; S3 Extended Request ID: NFavGKhGNy15+CMYxrKcV3nqH8M5h6//5eJ30UjTG9UFBSgtOe5KYjbVykKXQ0qWbE7Zt1h4wmk=; Proxy: null)

 -- Check script '/Users/sandmann/.nextflow/assets/nf-core/rnaseq/./workflows/../subworkflows/local/input_check.nf' at line: 33 or see '.nextflow.log' file for more details

```

**Comment by drpatelh** [comment]
Ah, sorry. This issue has got a little confused. There were 2 tests I mentioned:

1. By changing the parameters you provide when you run with a pipeline created with `nf-core create` as below:

> As a test you could try to download the fasta file via the AWS CLI and then run with the command below with your local credentials set. If this fixes it then we know it's an AWS iGenomes region issue:

> aws s3 cp --no-sign-request s3://ngi-igenomes/igenomes/Saccharomyces_cerevisiae/Ensembl/R64-1-1/Sequence/WholeGenomeFasta/genome.fa .
nextflow run nf-core-pipeline/ -profile test,docker --outdir test_run --genome false --fasta ./genome.fa

2. One with the test profile of nf-core/rnaseq 

> However, be interested to know if the same issue manifests with and without the credentials set for nf-core/rnaseq. If so, be great if you can open a separate issue on that repo too please.

> nextflow run nf-core/rnaseq -profile test,docker --outdir ./results

This should be fixed now because I changed the staging locations of the FastQ files from S3 to https:
https://github.com/nf-core/test-datasets/commit/6f4908cf0c39ddc278005e1a6a814a9422dc1c72
