### ISSUE TITLE
Poor error messages in samplesheets with incorrect number of columns

### ISSUE THREAD

**Issue by benbfly** [nf-core/tools#2255]
### Description of the bug

It's common for sample sheets to have optional columns at the end, which should be filled in with blank entries. For instance, in the following "fastq_2" and "barcode" are optional (samplesheet.csv):

```
sample,fastq_1,fastq_2,barcode
SAMPLE_PAIRED_END,/path/to/fastq/files/AEG588A1_S1_L002_R1_001.fastq.gz,,
SAMPLE_SINGLE_END,/path/to/fastq/files/AEG588A4_S4_L003_R1_001.fastq.gz,,

```

If people create/edit these sample sheets by hand, they might put the wrong number of trailing commas, like this (samplesheet_edited.csv):
```
sample,fastq_1,fastq_2,barcode
SAMPLE_PAIRED_END,/path/to/fastq/files/AEG588A1_S1_L002_R1_001.fastq.gz,
SAMPLE_SINGLE_END,/path/to/fastq/files/AEG588A4_S4_L003_R1_001.fastq.gz,

```

In this case, the template check_samplesheet.py will error out with the message
"The sample sheet **must** contain these column headers: fastq_1, fastq_2, sample."

This is a baffling error message, because the header line does indeed include those headers.

I would recommend adding additional error checking in check_samplesheet.py:sniff_format() to check and catch common formatting errors.  In the case above, the dialect it is getting is not even csv, it is getting a dialect.delimiter="p" which doesn't make any sense and should be caught.

### Command used and terminal output

```console
nf-core create
nextflow run ./nf-core-new/main.nf -profile docker --outdir "./testresults" --input ./nf-core-new/assets/samplesheet_edited.csv --genome GRCh38
```

### System information

N E X T F L O W  ~  version 23.04.0
 nf-core/tools version 2.7.2
executor local
OS Ubuntu
Python 3.8.3 (from quay.io/biocontainers/python:3.8.3)
Hardware (Azure VM)

**Comment by mirpedrol** [comment]
Hi @benbfly,
You can now use the nf-validation plugin instead of this module and subworkflow to validate an input sample sheet and create a channel from it.
You can find the [documentation](https://nextflow-io.github.io/nf-validation/) and an [example](https://github.com/nf-core/rnaseq/pull/1058) of how to use it with the nf-core template.
Using this plugin, as long as the columns are not required, they will be ignored and don't throw an error. It also allows the user to have extra columns.
