### ISSUE TITLE
Template: Better handling of `params.fasta` requirement

### ISSUE THREAD

**Issue by ewels** [nf-core/tools#2289]
### Description of feature

We currently have a check for `params.fasta` hardcoded into `lib/WorkflowPipeline.groovy`:

https://github.com/nf-core/tools/blob/0912990a63ef29e44e07cc2ba6ab81113684e0ae/nf_core/pipeline-template/lib/WorkflowPipeline.groovy#L18-L20

This is not very easy to find and tricky for people creating non-genomics pipelines.

Needs one or more of the following:

1. A `// TODO nf-core:` comment to flag it for review with `nf-core lint`
2. Some inclusion in the templating feature switches, to exclude it for non-genomics workflows
3. Moving out of `lib` to somewhere more visible? 🤔  eg. we already have similar checks here:
  https://github.com/nf-core/tools/blob/0912990a63ef29e44e07cc2ba6ab81113684e0ae/nf_core/pipeline-template/workflows/pipeline.nf#L17-L18

My preference would be (3) unless there's a specific reason for having it where it is currently.. @drpatelh ?

**Comment by drpatelh** [comment]
I put it in `lib/` so it sits with all of the other `params` checks we do so they are all together in a single `initialise` function and to avoid adding loads of boilerplate to the main workflows.

Think I added `input` in the main workflow because it is one of the only inputs that can be staged directly as a channel and doesn't need to pass through a module/sub-workflow like the reference files.

I would prefer (1) because you can quite easily search for the error code in VS code and find where it is.

(2) would be good either way.

**Comment by mirpedrol** [comment]
`params.fasta` is now outside of the lib directory and can be skipped when creating a pipeline
