### ISSUE TITLE
nf-core launch: revision selection broken

### ISSUE THREAD

**Issue by chasemc** [nf-core/tools#2360]
### Description of the bug

I thought it might just be non nf-core pipelines:
tools v2.8
![image](https://github.com/nf-core/tools/assets/18691127/91563bd5-ba6a-4128-b96b-c65c5f6fa93b)

tools v2.9
![image](https://github.com/nf-core/tools/assets/18691127/d6051b4f-1ae0-4a17-a6b6-63870b1b6471)

but rnaseq also not working:
![image](https://github.com/nf-core/tools/assets/18691127/7f16ba75-23da-4f8c-99a3-90a791fabcca)

### Command used and terminal output

```console
mamba create --name nf bioconda::nextflow>=23.04.1 bioconda::nf-core>=2.9
mamba activate nf
nf-core launch nf-core/rnaseq -r 3.12.0
```

    Hardware (Desktop)
    OS (ubuntu)
```


### System information

_No response_

**Comment by paoloAngelino** [comment]
I have the same issue with version v2.9, when selecting the rnaseq pipeline from the list:
`nf-core launch nf-core/rnaseq`
![Capture](https://github.com/nf-core/tools/assets/113043179/88480f0a-c6b7-41c1-a689-84b09d0c511a)

If I  specify the version at the command line it works:
`nf-core launch nf-core/rnaseq -r 3.12.0`
![Capture1](https://github.com/nf-core/tools/assets/113043179/9dbd99ff-73b6-426b-b831-9cf32bf45203)

**Comment by mashehu** [comment]
This is due to a bug after the launch of the new website. For nf-core website, you can in the mean time manually copy-paste the parameter file by going to the website of the pipeline of interest e.g. https://nf-co.re/rnaseq/3.12.0 and hit the launch button on top of that page. Go through all steps and att the end you can copy the parameters from the text field.
