### ISSUE TITLE
nf-core modules create {{ tool }} value is empty

### ISSUE THREAD

**Issue by mahesh-panchal** [nf-core/tools#2466]
### Description of the bug

When using `nf-core modules create tool/subtool` the {{tool}} value that is supposed to be in the template is not present.

E.g. versions.yml text looks like:
```
    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        : \$(echo \$(samtools --version 2>&1) | sed 's/^.*samtools //; s/Using.*\$//' ))
    END_VERSIONS
```
The `{{ tool }}` before the `:` is missing.

It's also missing in the tests/../test.yml. 
The TODO statement looks like:
```
## TODO nf-core: Please run the following command to build this file:
#                nf-core modules create-test-yml /stat
```
where ``{{ tool }}`` is missing before the `/`.

### Command used and terminal output

```console
$ nf-core modules create gfatools/stat
```

### System information

nf-core tools v2.10

**Comment by awgymer** [comment]
I believe this came about when we moved to `component` level  commands. 

The `CreateCommand` class no longer has a `self.tool` attribute but rather a `self.component` one (`self.subtool` remains unchanged). 

There are two approaches to fix this:
* update the template to use `{{ component }}` instead of `{{ tool }}`. 
* set `self.tool = self.component` for `ModuleCreate` (makes no sense in `SubworkflowCreate` really)
