### ISSUE TITLE
PermissonError when cachedir already exists

### ISSUE THREAD

**Issue by johnne** [nf-core/tools#292]
When running nf-core where `$TMPDIR/nfcore_cache` has already been set up from another user running nf-core on the same system you get a `PermissonError` from `utils.setup_requests_cachedir`.

**Comment by ewels** [comment]
@sven1103 - I'm thinking that we can perhaps strip out all `requests-cache` code from nf-core tools now, what do you think?

As I remember we mostly added it to avoid hitting the GitHub API rate limit. But now that we pull the pipeline info on the website instead and nf-core tools just fetches that file I suspect that it's not an issue any more.

**Comment by drpatelh** [comment]
@ewels I remember you providing a fix in the PR below due to something @Alastair Kerr reported on Slack (cant find the messages...). 
https://github.com/nf-core/tools/pull/221

Didnt it also have something to do with sending too many requests for conda packages too? Not sure if thats the same as the GitHub API rate limit.

If I remember correctly I have also had this issue recently with version 1.5 of `tools`. I just fixed it by deleting that directory but agree that its not really scalable.

**Comment by ewels** [comment]
@drpatelh - your memory is apparently significantly better than mine.. 🤦‍♂️ Yes, that sounds like exactly the same problem. And yes, it looks like I already fixed it.

@johnne - my guess is that @orzechoj ran nf-core tools before this bugfix was released, which created the cache with non world-writeable permissions.
@orzechoj if you're able to delete this file, I think that nf-core tools should go on to work normally for everyone.

Phil

**Comment by ewels** [comment]
Closing the issue now, but shout if this is not resolved.

**Comment by orzechoj** [comment]
> @orzechoj if you're able to delete this file, I think that nf-core tools should go on to work normally for everyone.

I deleted all files in $TMPDIR created by me. Hope it helps!

**Comment by ewels** [comment]
ok nice - thanks! As long as you're all running the latest release of `nf-core` I think you should be fine now... 🤞 

Shout if you have any problems!
