### ISSUE TITLE
`xx` is present as an output in meta.yml but not in main.nf

### ISSUE THREAD

**Issue by GallVp** [nf-core/tools#3097]
### Description of feature

For outputs of type `tuple val(meta), path("*.variants.tsv"), path("*.depth.tsv"), emit: variants`

`nf-core modules lint` produces a warning:

depths is present as an output in meta.yml but not in main.nf

Should this warning be removed?

**Comment by mirpedrol** [comment]
Hi @GallVp, 
Thank for reporting this, we are planning to fix the structure of all modules `meta.yml` files so that they contain the correct information (see https://github.com/nf-core/modules/pull/6015), this will be handled by nf-core/tools once [the new feature is merged](https://github.com/nf-core/tools/pull/3028).
