### ISSUE TITLE
Test pipelines with Singularity & Conda

### ISSUE THREAD

**Issue by mirpedrol** [nf-core/tools#3098]
### Description of feature

Pipelines are only tested with Docker. We should add tests with Singularity and Conda too.
Test with Singularity and Conda only on PRs to master + workflow dispatch. To avoid running the tests too often.
Linting: Singularity should be required, but Conda must be optional (opt-out) for pipelines which use custom Docker containers.

**Comment by edmundmiller** [comment]
Kinda a seperate issue but thought it might be a good place for the discussion.

I was thinking about this in terms of nf-core/modules. 

Since we use the merge_queue, what if we only ran singularity and conda when the merge_queue is ran? It seems like the conda environment creation in some modules takes a really long time to get created(and in nf-test it creates the environment every time).

**Comment by mashehu** [comment]
added in #3149
