### ISSUE TITLE
Template missing channels for fastqc and multiqc

### ISSUE THREAD

**Issue by matq007** [nf-core/tools#333]
The cookiecutter template is missing channels for both `fastqc` and `multiqc` in [environment.yml](https://github.com/nf-core/tools/blob/4ab80b83cd8b6562a88bb38b6aa0a3d082fd4de6/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/environment.yml#L10).

**Comment by drpatelh** [comment]
@matq007 I think we agreed that not to pin the channels if it can be avoided:
https://github.com/nf-core/methylseq/issues/74#issuecomment-467974219

Is this what you meant?

**Comment by matq007** [comment]
Ah interesting, I have different info from @apeltzer. Discussion [here](https://github.com/nf-core/rnafusion/pull/78#discussion_r284212467).

**Comment by drpatelh** [comment]
Maybe we didnt ALL agree then :laughing: Should probably revisit the discussion...

Another example where I was under the same impression:
https://github.com/nf-core/atacseq/pull/23#discussion_r262509934

**Comment by apeltzer** [comment]
So there is a couple of things with this that we should probably discuss out a bit. The discussion started here somehow (maybe earlier occasions available too, but thats the one I remember):

https://github.com/nf-core/cookiecutter/issues/45

It came back, when this here started due to slower conda resolving issues:

https://github.com/bioconda/bioconda-recipes/issues/13774


I guess we should just define what we want and keep the template set like this later - and then maybe make a comment why we settled it like this 👍 My impression was to have the prefixes for (`conda-forge/bioconda::`) doesn't really harm and makes it more explicit where packages are coming from (which I like a lot).
