### ISSUE TITLE
problem with nfcore_cache.sqlite within /tmp

### ISSUE THREAD

**Issue by lucacozzuto** [nf-core/tools#379]
Hi all,
I think will be a nice idea to have the nfcore_cache.sqlite within a subfolder in tmp because if two users use the program at the same time the privileges will prevent to use the tool.

For example I cannot even use nf-core --help 

Luca

**Comment by sven1103** [comment]
Thanks @lucacozzuto well spotted!

This is the code line that makes trouble:

https://github.com/nf-core/tools/blob/4ab80b83cd8b6562a88bb38b6aa0a3d082fd4de6/nf_core/utils.py#L79

I suggest to setup the cache directory locally in a folder `.nfcore_cache` in the user's home folder, instead of a system-wide available mount point.

Any objections?

**Comment by sven1103** [comment]
@ewels I know that you initially wanted to support a multi-tenant system and went for the `/tmp` dir. However, we don't know the system's file permission policy, and `chmod` will not always work (as happened here).

**Comment by apeltzer** [comment]
```bash
import tempfile
```

can be dropped due to https://lgtm.com/projects/g/nf-core/tools/rev/pr-78a866159bbc8065b95d1ea9b362de23429a32d8

**Comment by ewels** [comment]
Do we have any idea why this isn't working for multiple users at once? If it's world read-write then surely anyone should be able to use it?

**Comment by drpatelh** [comment]
@sven1103 Is whispering in my ear at the moment so forgive the typos because he isnt making any sense at all 😕 

Apparently, some systems dont allow you to change permissions with `chmod` so basically the file will only how those permissions at the user-level. The permissions wont be changed if nf-core/tools is creating a cache directory with 777 permissions by someone else. @sven1103 will try to reproduce it.

**Comment by ewels** [comment]
Don't worry about it @sven1103 - let's just use your homedir solution 👍
