### ISSUE TITLE
Description of nf-core create files

### ISSUE THREAD

**Issue by combiz** [nf-core/tools#390]
Would be useful to provide descriptive text of the files generated by `nf-core create` and the 'best practices' incorporated in the nf-core template.

**Comment by ewels** [comment]
Thanks for the suggestion @combiz - any thoughts about where on the website this should go? Where would you first look for it?

I'm thinking either _Adding a new pipeline_ or maybe as its own new page under _Developers_..

**Comment by combiz** [comment]
@ewels Thanks, either location sounds good -- perhaps the latter if there's a lot of ground to cover.  Linking to the page from the nf-core tools page (e.g. `nf-core create` under #creating-a-new-workflow) would be good also.

**Comment by drpatelh** [comment]
Great suggestion @combiz :+1: One of the main problems with having a standalone page on the website means that it could become outdated with new releases of the pipeline template. Do we provide a further "tab" on the website for documentation per release? Or maybe we add a markdown documentation file to the template that is linted to check when files are added/removed? Just chucking some raw thoughts out there but it would be nice to do this in a way that would require as little work as possible to maintain :sweat_smile:

**Comment by ewels** [comment]
I guess the same could be said for all of the documentation that we have though.. We could be clever with file manifests (including documentation) and linting and stuff like this, but I suspect that this will come at a cost of readability. And it's more work..!

My inclination here would be to make a new page in [nf-core/tools/docs](https://github.com/nf-core/tools/tree/master/docs) (so that it's linked to the release, as is the case with the lint error docs), and that we render this on the website. Maybe linked to from the `nf-core create` docs section only for now? So a new page, but not a new main nav link. We can also link to it from the tutorial and adding-a-new-pipeline docs and other relevant places of course.

I guess a basic lint test on tools that checks if template files have been added / removed would be fairly easy to make, that just checks that this markdown file has also been edited in the same PR..

**Comment by ewels** [comment]
Update: the tools documentation has been rewritten recently to build with Sphinx. This means that it is now easier to write structured docs within the tools repo that are reflected on the nf-core website. That way, the docs stay in sync with the package. This is what we do with the linting docs.

These new docs are still early days, so the styling doesn't match the rest of the website yet. And they're also fairly tricky to find. We're working on that..

* https://nf-co.re/tools-docs/
* https://github.com/nf-core/tools/tree/dev/docs/api/_src

**Comment by ewels** [comment]
Also, I think that this will be closed by https://github.com/nf-core/nf-co.re/pull/585
