### ISSUE TITLE
Launch should allow to choose between pipeline releases

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#422]
Currently, I think the `nf-core launch ...` command simply allows running the `master` branch. However, it would be great to also be able to launch any version of the specific pipeline available, e.g. similar to what Nextflow does with `-r ...`. 

Parameters might be different between releases, but if we have the JSON schema everywhere, that doesn't really matter 👍

**Comment by ewels** [comment]
For sure :+1: May need some thought as to how we fetch the parameter file, but should certainly be doable.

**Comment by ewels** [comment]
Found an issue with nextflow when looking into this. https://github.com/nextflow-io/nextflow/issues/1334

Note that `nf-core launch` works with local pipeline folders - using a `-r` flag here will have to trigger an error.

The command also it tries to use the cached copies of nextflow pipelines where possible. Using the `-r` flag will have to trigger a fresh pull of the pipeline. I don't see any problems with this though.

**Comment by ewels** [comment]
Done in https://github.com/nf-core/tools/pull/626

Also refactored the code so that it handles the `detached HEAD` thing that we get when you do `nextflow pull` on a specific version. So now `nf-core list` works in a much more useful way (and also prints more useful info about current local workflow states)
