### ISSUE TITLE
Redundant text in social preview

### ISSUE THREAD

**Issue by mashehu** [nf-core/tools#580]
What is the motivation behind having the short description of the pipelines as part of the social preview image? Most services I could test include that text in their preview cards, which creates a bit of a redundancy:
<img width="668" alt="Screenshot 2020-03-04 14 56 42" src="https://user-images.githubusercontent.com/6169021/75886721-f926e500-5e28-11ea-9381-da39673fdadb.png">

PS: I hope this is the correct repo for this issue 🙂

**Comment by MaxUlysse** [comment]
I did create all social previews myself, and I figured that it was good to have some description for the pipelines, so I took the text from the description.

I don't actually think it's a problem.
But what would you want to have instead?

**Comment by mashehu** [comment]
I would use the logo, which seems to be the standard for social previews (if they are not articles).
This would also allow to use the logo in other places, for example in the MultiQC reports.

**Comment by MaxUlysse** [comment]
I did got the inspiration of the design from the https://github.com/nf-core/tools/settings/og-template

**Comment by mashehu** [comment]
Here is an example, how github uses them (which looks to me more like for an article 🙂):
<img width="552" alt="Screenshot 2020-03-04 15 55 12" src="https://user-images.githubusercontent.com/6169021/75891907-bc5eec00-5e30-11ea-9948-d4df41ca00b3.png">

**Comment by MaxUlysse** [comment]
And I can see what is GitHub doing for their own stuff: https://twitter.com/gau/status/1235151595194773507

I do have more pressing issues at the moment, but if we're getting only the logo, we could actually automatize the generation of the social preview image (similar to what we're doing with https://nf-co.re/logo/automated?w=1280).
Just need to figure out the actual size of the stuff, and maybe resize the logo if it's too big.

**Comment by MaxUlysse** [comment]
So I'm trying out without any description for the new [nf-core/covid19
](https://github.com/nf-core/covid19) pipeline.
![Screenshot from 2020-03-17 07-50-15](https://user-images.githubusercontent.com/1019628/76829718-18a80f80-6824-11ea-9ea0-7a69894b7201.png)
@nf-core/core any preferences?

**Comment by mashehu** [comment]
Here's how it looks like on the different platforms:
![Screenshot_2020-03-17 Meta Tags — Preview, Edit and Generate(1)](https://user-images.githubusercontent.com/6169021/76850374-8a458500-6847-11ea-86d8-a0cde8fc6303.png)
![Screenshot_2020-03-17 Meta Tags — Preview, Edit and Generate](https://user-images.githubusercontent.com/6169021/76850402-9893a100-6847-11ea-8daa-b043adf2fe9a.png)
I prefer the no-text logo.

**Comment by MaxUlysse** [comment]
I like it without text as well.
Let's see what the rest of team like too.

**Comment by drpatelh** [comment]
Yeah, with the examples @mashehu sent I would say that the description is redundant. Would also make things much easier to automate without it.

**Comment by mashehu** [comment]
I think without the text we could even make the logo bigger, but I don't know if that creates problems with long pipeline names.

**Comment by MaxUlysse** [comment]
It'll create issue with pipelines with longer names.
I think it make sense since we do have plenty of pipeline to keep some kind of unity.
So I propose this size, as it's quite working well for our pipelines with the longest names.
Also, the logo should be centred horizontally, but not vertically, as all logos don't have the same heights (depending on letters and such).
But as it's something that needs to be done just once, and as I already have every thing done on my side, I'll update the social media images on github, and at some point I'll make PRs for that as well...

**Comment by ewels** [comment]
Note that not all platforms show the description text. eg. Mobile twitter client for me:

![5ED92D8A-43D1-4401-95DF-239FD9F7B945](https://user-images.githubusercontent.com/465550/77400970-5c62c200-6dac-11ea-8946-0de64c09d4ab.jpeg)

Though in this case of course we put the description text in the tweet itself (predates the social preview).

**Comment by drpatelh** [comment]
So we could just remove the description from the automated Tweet then? Will still mean @MaxUlysse has to create them manually though.

**Comment by ewels** [comment]
To be honest, I started posting to point out that we should keep the description text in the image as otherwise it could be lost on twitter. But once I put the screen grab in I realised that the tweet text had it 😅 

Generally I like having the description text underneath as I think that it's more attention grabbing - I am more likely to read that than read the text around the embed. It is very predictable and I don't mind the duplication. However I also see the attraction of automating this which is difficult with the description text.

Overall I don't see the need to go through all pipelines changing stuff as @MaxUlysse already did, but going forward I guess we could set up a social image logo automation script based on the existing logo one to make life easier for people. If we could use the GitHub API to set this I would be 100% backing this, but as it's still a manual upload I am slightly less fussed.

> I think without the text we could even make the logo bigger, but I don't know if that creates problems with long pipeline names.

I think lots of whitespace is not a bad thing, as these images often get cropped in weird ways. Having a buffer usually solves this.

I agree that the GitHub CLI one looks amazing 😍

**Comment by MaxUlysse** [comment]
Should we make a poll and let the community decide?

**Comment by mashehu** [comment]
Hmm, weird that twitter's own card validator doesn't include the mobile option, but I read now up on the twitter docs and unfortunately the `twitter:description` part is not supported on mobile 😞

**Comment by drpatelh** [comment]
No need for a poll. I think we can decide this amongst ourselves 😅 . I agree with @ewels 👍 I do like the text in the image too but I was just thinking about you having to manually do this every time we get a new pipeline which wont be much in reality. If we can automate it by other means then Im happy too.

**Comment by ewels** [comment]
x-ref: https://github.com/nf-core/nf-co.re/issues/176

**Comment by MaxUlysse** [comment]
I don't really mind making it every time, we don't have that many new pipelines.
And it can usually wait a couple of days.
