### ISSUE TITLE
Custom pipeline files incorrectly deleted in automated sync

### ISSUE THREAD

**Issue by Zethson** [nf-core/tools#581]
Ahoy :boat: 

Everytime I sync MHCquant all of the scripts in /bin get deleted. We know why it happens, but maybe there's some way of protecting them?
See: https://github.com/nf-core/mhcquant/pull/99/files

Maybe we can copy scripts in /bin (except version scraping) in an intermediate folder and then just copy them over after the fresh template was created and add them to the TEMPLATE PR?

**Comment by ewels** [comment]
Do we know why? I would have expected them to be safe, at least after a certain point, as git would understand their version history (and they’ve never been in `TEMPLATE`).. :thinking:

Phil

**Comment by Zethson** [comment]
Actually not I guess.
I'm sure that you know the feeling where something goes wrong and you create a story explaining why that must be the case? Likely happened to me here :)

I guess something must have gone wrong when setting up sync for MHCquant (did it manually) and it does not compare against the first commit or something along those lines?

**Comment by ewels** [comment]
Yes, possible. I would hope that it doesn’t happen a second time though.. That’s how these kind of sync weirdness things have gone with me in the past - the more times you sync the smoother it gets (with a big jump after n=1)

**Comment by Zethson** [comment]
Pretty sure that I've done it 3 times already with that issue, but I can keep you updated here :)

After my manual sync setup the PR was created automatically and successfully, so it is good to go.

**Comment by Zethson** [comment]
New PR for mhcquant looks fine.

Hence, I consider this issue "solved".

**Comment by ewels** [comment]
Hooray! Thanks for the update..

**Comment by Zethson** [comment]
https://github.com/nf-core/proteomicslfq/pull/101/files

Pops up again for proteomicslfq

**Comment by ewels** [comment]
We think that we have hopefully solved this now, it's due to the `TEMPLATE` branch being contaminated with development commits from `dev` when merge conflicts are solved.

The upcoming v1.13 release of tools uses a new method for the automatic sync where a new branch is created from `TEMPLATE` and a PR made from that. This can have merge conflicts solved back into that branch safely without affecting `TEMPLATE`. That, together with cleaning up the `TEMPLATE` branch in repos that are already problematic will hopefully solve this.

Worth additionally mentioning that v1.13 has stricter linting and automatic `--fix` functionality which will work well as a warm-up step to the template sync and hopefully reduce the diff (and so merge conflicts) considerably 🤞🏻  We're also moving as much boilerplate code out into `lib` files as possible for the same reason.
