### ISSUE TITLE
Check whether newer version of tools has been released

### ISSUE THREAD

**Issue by Zethson** [nf-core/tools#612]
## Issue

People keep creating templates or lint with old versions of tools. They are not always aware that a newer version of tools exists

## Proposed solution

This is one of many many possible solutions. We could check for a newer version on PyPi and warn the user with a red styled Click echo that a newer version exists. We could also at the same time possibly tell them how to upgrade or point to a link on the nf-core website about how to upgrade tools.

**Comment by ewels** [comment]
Equivalent code in MultiQC [here](https://github.com/ewels/MultiQC/blob/7685b9e06e3639fd918ef2b69b1d84d4f0b3b35d/multiqc/multiqc.py#L320-L330). Probably better to check PyPI though :+1:

**Comment by ewels** [comment]
With a little refactoring, may also be able to use the [`check_anaconda_package()` function from `lint.py`](https://github.com/nf-core/tools/blob/ebf63095ab222e4df987c4e950ce3839e8784d3e/nf_core/lint.py#L773) - this queries the Anaconda API to find the latest version available.

Or query PyPI. Or we can do what MultiQC does and have a file on the nf-core website with the latest version which we query. The latter is kind of fun because we can then track usage of nf-core/tools by counting how many times that file is pinged.
