### ISSUE TITLE
AWSFull doesn't run test_full profile

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#745]
While checking for a different issue we have, I found this in the comment:

https://github.com/nf-core/tools/blob/2e57264dbbc083bcd9624d781c000c82b331fdee/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/.github/workflows/awsfulltest.yml#L4

While the actual code runs profile `test`:

https://github.com/nf-core/tools/blob/2e57264dbbc083bcd9624d781c000c82b331fdee/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/.github/workflows/awsfulltest.yml#L42

**Comment by drpatelh** [comment]
Yup. That's because the data for the `test_full` profile needs to be added which is explained in the TODO statement above 🙂 
https://github.com/nf-core/tools/blob/2e57264dbbc083bcd9624d781c000c82b331fdee/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/.github/workflows/awsfulltest.yml#L28

**Comment by apeltzer** [comment]
Should read more and drink a coffee before posting issues ;-)
