### ISSUE TITLE
S3 bucket storage of certain files not supported

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#79]
cr:  https://github.com/nextflow-io/nextflow/issues/813

We can't (as of now) store trace files on an S3 Bucket, so specifying one to store data on when running  pipelines will crash in many cases where we store the trace file in the ``--outdir`` on S3.

**Comment by ewels** [comment]
In the short term, we should just overwrite the [`timeline.file`](https://github.com/nf-core/cookiecutter/blob/master/%7B%7Bcookiecutter.pipeline_slug%7D%7D/nextflow.config#L56) config (and others) in the [`aws.config`](https://github.com/nf-core/cookiecutter/blob/master/%7B%7Bcookiecutter.pipeline_slug%7D%7D/conf/aws.config) file so that they don't use `params.outdir`. This should fix the problem I think..?

**Comment by apeltzer** [comment]
Yup - I think so too! WIll test this with RNAseq in the next days once the profile is in there :-)

**Comment by apeltzer** [comment]
We have `tracedir = "${params.outdir}/pipeline_info"` present in the base profile, so this should be fine and done as well!
