### ISSUE TITLE
Linting should check pipeline names for guidelines

### ISSUE THREAD

**Issue by apeltzer** [nf-core/tools#85]
https://github.com/nf-core/ICGC-featureCounts/issues/8

**Comment by MaxUlysse** [comment]
Is the pipeline name following the lowercase convention an absolute requirement?

**Comment by ewels** [comment]
This becomes less important with new `nf-core create` name validation in https://github.com/nf-core/tools/pull/175 (but could still be nice and should be easy)

**Comment by ewels** [comment]
> _Is the pipeline name following the lowercase convention an absolute requirement?_

Up for discussion - the reason for this was that docker images are always lower case and without punctuation, so makes everything more consistent. Also just easier to remember if everything is always lower case.

NB: I remember way back thinking that the lint tool could be useful for people doing pipelines outside of nf-core (eg. forks). This test could be annoying there, so maybe good as a warning instead of a fail?

**Comment by apeltzer** [comment]
Yes, I think a warning is already sufficient, giving people feedback instead of just failing is better in such a case 👍
